class FillHr:
    def __init__(self, page):
        self.page = page

    def fillProfessionalInfo(self):
        self.page.get_by_role("tab", name="Documents").click()
        self.page.locator("//a//span[text()='HR']").click()
        self.page.locator("//span[text()='Professional Info']/parent::a")
        self.page.locator("//select[@name='certificatetype']").select_option("2")
        self.page.locator("input[name=\"dob\"]").click()
        self.page.locator("input[name=\"dob\"]").click()
        self.page.locator("input[name=\"dob\"]").fill("09/10/2023")
        self.page.locator("#txtLicenseNumber").click()
        self.page.locator("#txtLicenseNumber").fill("1234567")
        self.page.locator("#txtIssuedBy").click()
        self.page.locator("#txtIssuedBy").fill("Automation")
        self.page.locator("#txtValidationDate").click()
        self.page.locator("#txtValidationDate").click()
        self.page.locator("#txtValidationDate").fill("09/10/2023")
        self.page.locator("#txtExpires").click()
        self.page.locator("#txtExpires").click()
        self.page.locator("#txtExpires").fill("09/10/2024")
        self.page.locator("#txtnpi").click()
        self.page.locator("#txtnpi").fill("12")
        self.page.locator("#txthomecareRegistry").click()
        self.page.locator("#txthomecareRegistry").fill("automation")
        self.page.locator("#txtWorkTypeRequested").click()
        self.page.locator("#txtWorkTypeRequested").fill("permament")
        self.page.locator("#txthourlypay").click()
        self.page.locator("#txthourlypay").fill("100")
        self.page.locator("input[name=\"hiringDetails\\.dobProof\\.IsChecked\"]").check()
        self.page.locator("#txtRecruiter").click()
        self.page.locator("#txtRecruiter").fill("Automation")
        self.page.locator("#ddncitizenshipstatus").select_option("2")
        self.page.locator("input[name=\"hiringDetails\\.i9Cleared\\.IsChecked\"]").check()
        self.page.locator("#txti9Expires").click()
        self.page.locator("#txti9Expires").click()
        self.page.locator("#txti9Expires").fill("09/10/2023")
        self.page.get_by_role("button", name=" Save Changes").click()

    def fillPayroll(self):
        self.page.locator("//a//span[text()='HR']").click()
        self.page.get_by_role("tab", name="Payroll").click()
        self.page.get_by_role("button", name=" Modify Employee").click()
        self.page.locator("app-emp-payroll #txtdateOfHire").click()
        self.page.locator("app-emp-payroll #txtdateOfHire").click()
        self.page.locator("app-emp-payroll #txtdateOfHire").click()
        self.page.locator("app-emp-payroll #txtdateOfHire").click()
        self.page.locator("app-emp-payroll #txtdateOfHire").press("ArrowRight")
        self.page.locator("app-emp-payroll #txtdateOfHire").press("ArrowRight")
        self.page.locator("app-emp-payroll #txtdateOfHire").fill("09/10/2023")
        self.page.locator("app-emp-payroll #txtdateOfFirstCase").click()
        self.page.locator("app-emp-payroll #txtdateOfFirstCase").fill("09/11/2023")
        self.page.get_by_role("textbox", name="Dependents").click()
        self.page.get_by_role("textbox", name="Employee ID").click()
        self.page.get_by_role("textbox", name="Employee ID").fill("12341")
        self.page.locator("app-emp-payroll #ddlmaritalStatus").select_option("5")
        self.page.locator("app-emp-payroll #ddlhRSupervisor").select_option("1")
        self.page.get_by_role("button", name=" Save Employee").click()

    def fillDirectDeposit(self):
        self.page.get_by_role("tab", name="Documents").click()
        self.page.locator("//a//span[text()='HR']").click()
        self.page.get_by_role("tab", name="Direct Deposit").click()
        self.page.locator("#ddnaccounttype").select_option("3")
        self.page.get_by_placeholder("Routing Number").click()
        self.page.get_by_placeholder("Routing Number").fill("12345")
        self.page.get_by_placeholder("Account Number").click()
        self.page.get_by_placeholder("Account Number").fill("123444")
        self.page.get_by_placeholder("Amount").click()
        self.page.get_by_placeholder("Amount").fill("1000")
        self.page.get_by_placeholder("Name On Account").click()
        self.page.get_by_placeholder("Name On Account").fill("Automation")
        self.page.get_by_role("button", name=" Save").click()