class Rate:
    def __init__(self,page):
        self.page=page

    def addRate(self):
        self.page.get_by_role("tab", name="Rates").click()
        self.page.get_by_role("link", name=" Add Rate").click()
        self.page.get_by_placeholder("Effective Date").click()
        self.page.get_by_placeholder("Effective Date").click()
        self.page.get_by_placeholder("Effective Date").fill("09/09/2023")
        self.page.get_by_placeholder("End Date").click()
        self.page.get_by_placeholder("End Date").fill("09/10/2024")
        self.page.get_by_placeholder("End Date").click()
        self.page.locator("input[name=\"Hourly\"]").click()
        self.page.locator("input[name=\"Hourly\"]").fill("12")
        self.page.locator("input[name=\"Livein\"]").click()
        self.page.locator("input[name=\"Livein\"]").fill("0")
        self.page.locator("input[name=\"OverHourly\"]").click()
        self.page.locator("input[name=\"OverHourly\"]").fill("12")
        self.page.locator("input[name=\"OverLivein\"]").click()
        self.page.locator("input[name=\"OverLivein\"]").fill("0")
        self.page.locator("#chkbxapplyRateCheck").check()
        self.page.get_by_role("button", name=" Save Rates").click()
        self.page.get_by_role("link", name=" Add Rate").click()
        self.page.get_by_placeholder("Effective Date").click()
        self.page.get_by_placeholder("Effective Date").click()
        self.page.get_by_placeholder("Effective Date").fill("09/09/2023")
        self.page.get_by_placeholder("End Date").click()
        self.page.get_by_placeholder("End Date").fill("09/09/2024")
        self.page.get_by_placeholder("End Date").click()
        self.page.locator("input[name=\"Hourly\"]").click()
        self.page.locator("input[name=\"Hourly\"]").fill("15")
        self.page.locator("input[name=\"Livein\"]").click()
        self.page.locator("input[name=\"Livein\"]").fill("0")
        self.page.locator("input[name=\"OverHourly\"]").click()
        self.page.locator("input[name=\"OverHourly\"]").fill("15")
        self.page.locator("input[name=\"OverLivein\"]").click()
        self.page.locator("input[name=\"OverLivein\"]").fill("0")
        self.page.locator("#chkbxapplyRateCheck").check()
        self.page.locator("select[name=\"PayerId\"]").select_option("72")
        self.page.locator("select[name=\"ClientId\"]").select_option("469")
        self.page.get_by_role("button", name=" Save Rates").click()