from time import sleep

from playwright.sync_api import Playwright, sync_playwright, expect


class PersonalInfo:
    def __init__(self,page):
        self.page = page


    def CreateEditPersonalInfo(self):
        self.page.get_by_role("link", name=" Clients").is_visible()
        self.page.get_by_role("link", name=" Clients").click()
        sleep(20)
        self.page.get_by_role("button", name=" Add Client").is_visible()
        self.page.get_by_role("button", name=" Add Client").click()
        self.page.locator("#txtclientStatus").select_option("2")
        self.page.locator("#txtclientStatus").select_option("1")
        self.page.get_by_placeholder("First Name").click()
        self.page.get_by_placeholder("First Name").fill("AutomationFirst")
        self.page.get_by_placeholder("Last Name").click()
        self.page.get_by_placeholder("Last Name").fill("AutomationLast")
        self.page.get_by_placeholder("SSN").click()
        self.page.get_by_placeholder("SSN").fill("123-45-67823")
        self.page.get_by_placeholder("Email", exact=True).click()
        self.page.get_by_placeholder("Email", exact=True).fill("automate123@gmail.com")
        self.page.get_by_placeholder("Primary Contact No").click()
        self.page.get_by_placeholder("Primary Contact No").fill("(718) 697-9823")
        self.page.get_by_placeholder("Secondary Contact No").click()
        self.page.get_by_placeholder("Secondary Contact No").fill("(783) 982-64233")
        self.page.get_by_placeholder("MM/DD/YYYY").click()
        self.page.get_by_placeholder("MM/DD/YYYY").click()
        self.page.get_by_placeholder("MM/DD/YYYY").fill("05/09/1990")
        self.page.locator("#ddlgender").select_option("10")
        self.page.locator("#ddethnicity").select_option("11")
        self.page.get_by_placeholder("Address", exact=True).click()
        self.page.get_by_placeholder("Address", exact=True).fill("florida")
        self.page.get_by_placeholder("Apt / Unit").click()
        self.page.get_by_placeholder("Apt / Unit").fill("1234")
        self.page.get_by_placeholder("City").click()
        self.page.get_by_placeholder("City").fill("NewYork")
        self.page.get_by_placeholder("Zip Code", exact=True).click()
        self.page.get_by_placeholder("Zip Code", exact=True).fill("123445")
        self.page.locator("#ddlcoordinator").select_option("2")
        self.page.locator("#ddlnurse").select_option("723")
        self.page.get_by_placeholder("Referred By").click()
        self.page.get_by_placeholder("Referred By").fill("Byautomation")
        self.page.get_by_placeholder("Alt. ID").click()
        self.page.get_by_placeholder("Alt. ID").fill("233")
        self.page.get_by_placeholder("ID 2").click()
        self.page.get_by_placeholder("ID 2").fill("3443")
        self.page.get_by_placeholder("ID 3").click()
        self.page.get_by_placeholder("ID 3").fill("423423")
        self.page.get_by_placeholder("Insurance ID").click()
        self.page.get_by_placeholder("Insurance ID").fill("12345678233")
        self.page.get_by_placeholder("Worker Name").click()
        self.page.get_by_placeholder("Worker Name").fill("Automation")
        self.page.get_by_role("textbox", name="(123) 123-1234").click()
        self.page.get_by_role("textbox", name="(123) 123-1234").fill("(123) 344-55677")
        self.page.get_by_placeholder("Priority Code").click()
        self.page.get_by_placeholder("Priority Code").fill("03")
        self.page.locator("//button[text()='Save Client']").click()
        sleep(5)
        self.page.locator("//a/span[text()='Dashboard']").click()
        sleep(5)
        clientId=self.page.locator("//span[text()='Client ID:']/../following-sibling::strong").text_content()
        sleep(5)
        return str(clientId)

